[package]
name = "kurookku/topbarplusfork"
description = "A fork for Wally/Rojo support"
license = "MPL2"
version = "3.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]